@echo off
REM bluud:managed
REM
REM Bluud memory pull hook (Windows).
REM
REM This file is generated by the Bluud CLI from the template shipped inside the
REM `bluud-cli` package (`src/hooks/bluud-pull-hook.cmd`). Running `bluud` again
REM rewrites it in place, which is also how a stale interpreter path heals
REM itself: the tool's own config only ever references this script, never the
REM volatile path of the `bluud` executable, so the entry a tool stores never
REM goes stale.
REM
REM Deleting the `bluud:managed` line above makes the CLI treat this file as
REM user-authored and leave it untouched from then on (it will also stop
REM removing it on `bluud uninstall`).
REM
REM Fail-open contract — BLUUD_CONCEPT.md section 9.1: "If the pull fails for
REM any reason (network error, invalid token, server unavailability), the agent
REM proceeds without memory and logs a warning to the conversation. It does not
REM block or interrupt the user's session."
REM
REM `bluud pull` writes the memory tree to stdout only after the request has
REM succeeded, and routes every diagnostic (errors, quota warnings) to stderr.
REM So on failure stdout is empty and this script exits 0 with the diagnostic
REM already forwarded to stderr.
REM
REM The `.cmd` extension is used rather than `.bat` so the script runs under
REM cmd.exe and under the Git Bash shell some tools spawn on Windows; the path
REM the tool stores uses forward slashes for the same reason (Git Bash treats a
REM backslash as an escape character).
REM
REM An empty format substitution leaves BLUUD_FORMAT undefined — `set "VAR="`
REM clears the variable in cmd — which is exactly what `if defined` tests below.

setlocal

set "BLUUD_BINARY=@BLUUD_BINARY@"
set "BLUUD_FORMAT=@BLUUD_FORMAT@"

REM `call` is required, not stylistic: npm installs `bluud` on Windows as a
REM `.cmd` shim, and cmd.exe *transfers control* to a batch file invoked
REM without `call` — the rest of this script would never run and the shim's
REM exit code would become the hook's, defeating the fail-open contract above.
REM `call` also works unchanged for a real `.exe`.
if defined BLUUD_FORMAT (
  call "%BLUUD_BINARY%" pull --inject --format=%BLUUD_FORMAT%
) else (
  call "%BLUUD_BINARY%" pull --inject
)

if errorlevel 1 (
  (echo bluud: memory pull failed; continuing without project memory.)1>&2
)

endlocal
exit /b 0
