#!/usr/bin/env sh
# bluud:managed
#
# Bluud memory pull hook (POSIX shell).
#
# This file is generated by the Bluud CLI from the template shipped inside the
# `bluud-cli` package (`src/hooks/bluud-pull-hook.sh`). Running `bluud` again
# rewrites it in place, which is also how a stale interpreter path heals itself:
# the tool's own config only ever references this script, never the volatile
# path of the `bluud` executable, so the entry a tool stores never goes stale.
#
# Deleting the `bluud:managed` line above makes the CLI treat this file as
# user-authored and leave it untouched from then on (it will also stop removing
# it on `bluud uninstall`).
#
# Fail-open contract — BLUUD_CONCEPT.md section 9.1: "If the pull fails for any
# reason (network error, invalid token, server unavailability), the agent
# proceeds without memory and logs a warning to the conversation. It does not
# block or interrupt the user's session."
#
# `bluud pull` writes the memory tree to stdout only after the request has
# succeeded, and routes every diagnostic (errors, quota warnings) to stderr. So
# on failure stdout is empty and this script exits 0 with the diagnostic already
# forwarded to stderr. That matters most for the hook contracts that parse
# stdout as a single JSON object (Gemini CLI's SessionStart,
# Cline's TaskStart): empty output is a well-formed "this hook contributed
# nothing", whereas a non-zero exit or a half-written payload is reported to the
# user as a broken hook.
#
# Hook payloads arrive on stdin (Cline's TaskStart JSON, Claude Code's
# SessionStart JSON). `bluud pull` needs none of them, so stdin is left unread.

BLUUD_BINARY='@BLUUD_BINARY@'
BLUUD_FORMAT='@BLUUD_FORMAT@'

bluud_failed=''

if [ -n "$BLUUD_FORMAT" ]; then
  "$BLUUD_BINARY" pull --inject "--format=$BLUUD_FORMAT" || bluud_failed=1
else
  "$BLUUD_BINARY" pull --inject || bluud_failed=1
fi

if [ -n "$bluud_failed" ]; then
  echo "bluud: memory pull failed; continuing without project memory." >&2
fi

exit 0
