// Bluud memory extension for Pi (earendil-works/pi).
// bluud:managed
//
// This file is generated by the Bluud CLI from the template shipped inside the
// `bluud` package (`src/hooks/bluud-pi-extension.ts`). Running `bluud` again
// rewrites it in place, which is how a stale `bluud` path heals itself.
//
// Deleting the `bluud:managed` line above makes the CLI treat this file as
// user-authored and leave it untouched from then on (it will also stop removing
// it on `bluud uninstall`).
//
// WHY AN EXTENSION AND NOT A HOOK ENTRY
//
// Pi has no hooks section in any config file — by design. Its integration
// surface is an extension module that receives the agent object and subscribes
// to lifecycle events. So for Pi, "installing a hook" means writing this file;
// there is no settings key to merge.
//
// Three events matter here, and they have to be used together:
//
//   session_start       Fires once per session. Pi resets per-session state
//                       here, so this is where the injection latch is cleared.
//   before_agent_start  Fires before the agent loop's first LLM call. This is
//                       the correct place to *fetch* memory, but it cannot
//                       mutate the message array itself — so it parks the text.
//   context             Fires before each LLM call with a mutable `messages`
//                       array. This is the only place text can actually enter
//                       the conversation, so the parked text is appended here
//                       and the latch cleared so it happens exactly once.
//
// The text is appended as a tail user message rather than folded into the
// system prompt: a systemPrompt change sits at messages[0] and invalidates
// prefix prompt caching for the whole session.
//
// FAIL-OPEN CONTRACT — BLUUD_CONCEPT.md section 9.1: "If the pull fails for any
// reason (network error, invalid token, server unavailability), the agent
// proceeds without memory and logs a warning to the conversation. It does not
// block or interrupt the user's session." Every failure path below therefore
// swallows its error and leaves the session running with no memory injected.

import { spawnSync } from "node:child_process";

// Substituted by the adapter at write time. The value is a JSON literal, so a
// Windows path's backslashes survive intact without any escaping of our own.
const BLUUD_BINARY: string = @BLUUD_BINARY@;

// How long to wait for `bluud pull`. One HTTPS round trip in the honest case;
// the bound exists so an unreachable API delays the first turn by seconds
// rather than hanging it. Pi's own session start is not blocked by this — only
// the first LLM call is, and only on the first turn of the session.
const PULL_TIMEOUT_MS = 30000;

/**
 * Run `bluud pull --inject --index` and return the memory index, or an empty
 * string when anything at all goes wrong.
 *
 * `--index` fetches the lightweight index (titles, ids, hierarchy,
 * descriptions) and never node bodies: this runs before there is a user
 * request to judge relevance against, so the agent decides what it needs once
 * it sees one and loads it with `bluud pull --inject --id <uuid>` itself.
 *
 * No `--format`: Pi consumes plain text, since this extension does the
 * envelope work itself by constructing the message object below. That is the
 * whole reason Pi needs no hook-output format of its own.
 */
function pullMemoryIndex(cwd: string): string {
  try {
    const result = spawnSync(BLUUD_BINARY, ["pull", "--inject", "--index"], {
      cwd,
      encoding: "utf8",
      timeout: PULL_TIMEOUT_MS,
      // stdin is ignored: `bluud pull` reads no payload, and leaving it
      // inherited risks consuming input the agent itself is waiting on.
      stdio: ["ignore", "pipe", "pipe"],
    });

    if (result.error || result.status !== 0) {
      warn(result.stderr);
      return "";
    }
    return (result.stdout || "").trim();
  } catch {
    // Binary missing, spawn failure, permissions — all non-fatal.
    return "";
  }
}

function warn(detail: unknown): void {
  const suffix = typeof detail === "string" && detail.trim() ? ` ${detail.trim()}` : "";
  try {
    process.stderr.write(`bluud: memory pull failed; continuing without project memory.${suffix}\n`);
  } catch {
    // stderr unavailable — nothing further to do.
  }
}

export default function (pi: any) {
  // Text fetched but not yet appended to a message array. Empty means either
  // "not fetched yet" or "already injected"; `injected` disambiguates so a
  // failed pull is not retried on every LLM call of the session.
  let pending = "";
  let injected = false;

  // Pi resets per-session state on session_start, so the latch is cleared here
  // rather than at module scope — a module-level flag would persist across
  // sessions in the same process and suppress injection for every session but
  // the first.
  pi.on("session_start", () => {
    pending = "";
    injected = false;
  });

  // Fetch once, before the first LLM call. This event cannot mutate messages,
  // so the result waits for `context`.
  pi.on("before_agent_start", () => {
    if (injected) return;
    injected = true;
    pending = pullMemoryIndex(pi?.cwd ?? process.cwd());
  });

  // The one place text can enter the conversation.
  pi.on("context", (event: any) => {
    if (!pending) return;
    const text = pending;
    pending = "";
    try {
      if (event && Array.isArray(event.messages)) {
        event.messages.push({ role: "user", content: text });
        return { messages: event.messages };
      }
    } catch {
      // Never break context assembly over memory injection.
    }
    return;
  });
}
